spring:
  application:
    name: eurekafargatesample
server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://myuser:mypwd@localhost:8761/eureka/
  instance:
    preferIpAddress: true